FROM node:20-alpine AS build
WORKDIR /app
COPY package.json tsconfig.json ./
COPY src ./src
COPY proto ./proto
RUN npm install
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package.json ./package.json
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
COPY --from=build /app/proto ./proto
EXPOSE 4000
CMD ["node", "dist/server.js"]
